### ISSUE TITLE
Has the package been unpublished from NPM?

### ISSUE THREAD

**Issue by kuriositeetti** [cedx/reverse-proxy.js#19]
The package is no longer available in NPM.

**Comment by cedx** [comment]
Exactly! I no longer maintain this project: I have abandoned it.
NPM allowed me to remove the package because it is not really downloaded anymore (cf. https://docs.npmjs.com/policies/unpublish).

There's **much better** alternatives like Apache/Caddy/NGINX or one of these packages if you have very specific needs:
- https://www.npmjs.com/package/proxy
- https://www.npmjs.com/package/http-proxy-middleware
- https://www.npmjs.com/package/http-proxy

**Comment by kuriositeetti** [comment]
Thanks for the info.
